version: '3.9'
services:
  next-app:
    build:
      context: ./docker/node/
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd app && npm run dev"
    tty: true
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - default

  mysql-db:
    build:
      context: ./docker/mysql/
      dockerfile: Dockerfile.database
    volumes:
      - db-store:/var/lib/mysql
      - ./db/conf/my.conf:/ect/mysql/conf.d/my.cnf
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - default

volumes:
  db-store:

networks:
  default:
    driver: bridge